blank_issues_enabled: false
contact_links:
  - name: Questions or Discussions
    url: https://github.com/saumyayadav25/cpp-dsa-sheet-testing/discussions
    about: Ask questions and discuss ideas here before filing issues.